name: sound_studio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  audioplayers: ^6.1.0
  camera: ^0.11.0+2
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.3.0
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  graphic: ^2.5.0
  http_parser: ^4.0.2
  intl: ^0.19.0
  mime: ^2.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_login_icon.png
    - assets/images/naver_login_icon.png
    - assets/images/kakao_login_icon.png
    - assets/images/left_arrow.png
    - assets/images/right_arrow.png
    - assets/audio/white_noise.mp3
    - assets/audio/pink_noise.mp3
    - assets/audio/green_noise.mp3