name: sound_studio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_login.png
    - assets/google_login_small.png
    - assets/kakao_login_medium_wide.png
    - assets/naver_login.png
    - assets/google_login_icon.png
    - assets/naver_login_icon.png
    - assets/kakao_login_icon.png
    - assets/left_arrow.png
    - assets/right_arrow.png